# Generated by Django 3.2.23 on 2023-12-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='order_number_inquiry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
